# Generated by Django 4.1.1 on 2022-09-15 04:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0004_bar_games_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
