# Generated by Django 4.1.1 on 2022-09-17 05:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0008_alter_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=b'I01\n', max_length=255, verbose_name='image'),
        ),
    ]
