# Generated by Django 4.1.1 on 2022-09-17 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0009_alter_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='timeofpost',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 5, 24, 50, 668964)),
        ),
    ]
