# Generated by Django 4.1.1 on 2022-09-17 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0011_games_teamone_games_teamtwo_alter_games_timeofpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='timeofpost',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 5, 30, 50, 381373)),
        ),
    ]
